// FIDE member federations (national chess federations), alphabetical.
// Compiled from FIDE's published federation list. FIDE membership/naming
// changes occasionally (new federations, renamed ones) — if this list is
// missing something current, cross-check https://directory.fide.com and
// add it; this isn't pulled live from FIDE.
export const FIDE_FEDERATIONS = [
  "Afghanistan Chess Federation (ACF)",
  "Albanian Chess Federation (FSHSH)",
  "Algerian Chess Federation (FAE)",
  "Andorran Chess Federation (FEVA)",
  "Angolan Chess Federation (FAX)",
  "Antigua and Barbuda Chess Federation (ABCF)",
  "Argentine Chess Federation (FADA)",
  "Chess Federation of Armenia (CFA)",
  "Aruba Chess Federation (FACA)",
  "Chess Association of Australia (CAA)",
  "Austrian Chess Federation (ÖSB)",
  "Azerbaijan Chess Federation (ACF)",
  "Bahamas Chess Federation (BCF)",
  "Bahrain Chess Federation (BCF)",
  "Bangladesh Chess Federation (BCF)",
  "Barbados Chess Federation (BCF)",
  "Belarusian Chess Federation (BCF)",
  "Royal Belgian Chess Federation (RBCF / FRBE-KBSB)",
  "Belize Chess Federation (BCF)",
  "Bermuda Chess Association (BCA)",
  "Bhutan Chess Federation (BCF)",
  "Bolivian Chess Federation (FEB)",
  "Chess Federation of Bosnia and Herzegovina (ŠSBiH)",
  "Botswana Chess Federation (BCF)",
  "Brazilian Chess Confederation (CBX)",
  "British Virgin Islands Chess Federation (BVICF)",
  "Brunei Darussalam Chess Federation (BDCF)",
  "Bulgarian Chess Federation (BCF)",
  "Burkina Faso Chess Federation (FBE)",
  "Burundi Chess Federation (FBE)",
  "Cambodian Chess Federation (CCF)",
  "Cameroon Chess Federation (FECAECHECS)",
  "Chess Federation of Canada (CFC)",
  "Cape Verde Chess Federation (FCX)",
  "Cayman Islands Chess Federation (CICF)",
  "Central African Chess Federation (FCAE)",
  "Chad Chess Federation (FTDE)",
  "Chilean Chess Federation (AJEFECH)",
  "Chinese Chess Association (CCA)",
  "Chinese Taipei Chess Association (CTCA)",
  "Colombian Chess Federation (FECODAZ)",
  "Comoros Chess Federation (FCC)",
  "Congolese Chess Federation (FECOCHE)",
  "Costa Rican Chess Federation (FENAC)",
  "Croatian Chess Federation (HŠS)",
  "Cuban Chess Federation (FCA)",
  "Cyprus Chess Federation (CCF)",
  "Czech Chess Federation (ŠSČR)",
  "Danish Chess Union (DSU)",
  "Djibouti Chess Federation (FDE)",
  "Dominica Chess Federation (DCF)",
  "Dominican Chess Federation (FEDOM)",
  "Ecuadorian Chess Federation (FEDA)",
  "Egyptian Chess Federation (ECF)",
  "El Salvador Chess Federation (FSA)",
  "English Chess Federation (ECF)",
  "Equatorial Guinea Chess Federation (FEGUIAJEDREZ)",
  "Eritrean Chess Federation (ECF)",
  "Estonian Chess Federation (ESL)",
  "Eswatini Chess Federation (ESCF)",
  "Ethiopian Chess Federation (ECF)",
  "Faroe Islands Chess Federation (TSF)",
  "Fiji Chess Federation (FCF)",
  "Finnish Chess Federation (SSL)",
  "French Chess Federation (FFE)",
  "Gabon Chess Federation (FGA)",
  "Gambia Chess Federation (GCF)",
  "Georgian Chess Federation (GCF)",
  "German Chess Federation (DSB)",
  "Ghana Chess Association (GCA)",
  "Hellenic Chess Federation (HSF)",
  "Greenland Chess Federation (GKF)",
  "Grenada Chess Federation (GCF)",
  "Guam Chess Federation (GCF)",
  "Guatemalan Chess Federation (FNA)",
  "Guernsey Chess Federation (GCF)",
  "Guyana Chess Federation (GuyCF)",
  "Haiti Chess Federation (FHE)",
  "Honduran Chess Federation (FENAH)",
  "Hong Kong China Chess Federation (HKCCF)",
  "Hungarian Chess Federation (MSSZ)",
  "Icelandic Chess Federation (TSÍ)",
  "All India Chess Federation (AICF)",
  "Indonesian Chess Association (PERCASI)",
  "Iran Chess Federation (ICF)",
  "Iraqi Chess Federation (ICF)",
  "Irish Chess Union (ICU)",
  "Isle of Man Chess Association (IoMCA)",
  "Israel Chess Federation (ICF)",
  "Italian Chess Federation (FSI)",
  "Ivorian Chess Federation (FCI)",
  "Jamaica Chess Federation (JCF)",
  "Japan Chess Federation (JCF)",
  "Jersey Chess Federation (JCF)",
  "Jordan Chess Federation (JCF)",
  "Kazakhstan Chess Federation (KCF)",
  "Chess Kenya (KEN)",
  "Kosovo Chess Federation (FShK)",
  "Kuwait Chess Federation (KCF)",
  "Kyrgyz Chess Union (KCU)",
  "Laos Chess Federation (LCF)",
  "Latvian Chess Federation (LŠF)",
  "Lebanese Chess Federation (LCF)",
  "Lesotho Chess Federation (LeCF)",
  "Liberia Chess Federation (LCF)",
  "Libyan Chess Federation (LCF)",
  "Liechtenstein Chess Federation (LSV)",
  "Lithuanian Chess Federation (LŠF)",
  "Luxembourg Chess Federation (FLDE)",
  "Macau Chess Federation (MCF)",
  "Madagascar Chess Federation (FME)",
  "Malawi Chess Association (MCA)",
  "Malaysian Chess Federation (MCF)",
  "Maldives Chess Association (MCA)",
  "Malian Chess Federation (FEMA)",
  "Malta Chess Federation (MCF)",
  "Mauritanian Chess Federation (FMA)",
  "Mauritius Chess Federation (MCF)",
  "National Chess Federation of Mexico (FENAMAC)",
  "Chess Federation of the Republic of Moldova (FCRM)",
  "Monaco Chess Federation (FCM)",
  "Mongolian Chess Federation (MCF)",
  "Montenegro Chess Federation (ŠSCG)",
  "Royal Moroccan Chess Federation (FRME)",
  "Mozambique Chess Federation (FMX)",
  "Myanmar Chess Federation (MCF)",
  "Namibia Chess Federation (NCF)",
  "Nauru Chess Federation (NCF)",
  "Nepal Chess Association (NCA)",
  "Royal Dutch Chess Federation (KNSB)",
  "Netherlands Antilles Chess Federation (NACF)",
  "New Caledonia Chess League (LENC)",
  "New Zealand Chess Federation (NZCF)",
  "Nicaraguan Chess Federation (FENIC)",
  "Niger Chess Federation (FENIJEC)",
  "Nigeria Chess Federation (NCF)",
  "Chess Federation of North Macedonia (CFNM)",
  "Norwegian Chess Federation (NSF)",
  "Oman Chess Committee (OCC)",
  "Pakistan Chess Federation (PCF)",
  "Palau Chess Federation (PCF)",
  "Palestinian Chess Federation (PCF)",
  "Panamanian Chess Federation (FNAP)",
  "Papua New Guinea Chess Federation (PNGCF)",
  "Paraguayan Chess Federation (FEPARAJ)",
  "Peruvian Chess Sports Federation (FDPA)",
  "National Chess Federation of the Philippines (NCFP)",
  "Polish Chess Federation (PZSzach)",
  "Portuguese Chess Federation (FPX)",
  "Puerto Rico Chess Federation (FAPR)",
  "Qatar Chess Association (QCA)",
  "Romanian Chess Federation (FRȘah)",
  "Chess Federation of Russia (CFR)",
  "Rwanda Chess Federation (RCF)",
  "St. Kitts and Nevis Chess Federation (SKNCF)",
  "Saint Lucia Chess Federation (SLCF)",
  "St. Vincent and the Grenadines Chess Federation (SVGCF)",
  "San Marino Chess Federation (FSM)",
  "São Tomé and Príncipe Chess Federation (FXSTP)",
  "Saudi Chess Federation (SCF)",
  "Chess Scotland (CS)",
  "Senegalese Chess Federation (FSE)",
  "Chess Federation of Serbia (ŠSS)",
  "Seychelles Chess Federation (SCF)",
  "Sierra Leone Chess Association (SLCA)",
  "Singapore Chess Federation (SCF)",
  "Slovak Chess Federation (SŠZ)",
  "Slovenian Chess Federation (ŠZS)",
  "Solomon Islands Chess Federation (SICF)",
  "Somali Chess Federation (SCF)",
  "Chess South Africa (CSA)",
  "Korea Chess Federation (KCF)",
  "South Sudan Chess Federation (SSCF)",
  "Spanish Chess Federation (FEDA)",
  "Chess Federation of Sri Lanka (CFSL)",
  "Sudanese Chess Federation (SCF)",
  "Suriname Chess Federation (SCF)",
  "Swedish Chess Federation (SSF)",
  "Swiss Chess Federation (SSB)",
  "Syrian Arab Chess Federation (SACF)",
  "Tajikistan Chess Federation (TCF)",
  "Tanzania Chess Association (TCA)",
  "Thailand Chess Association (TCA)",
  "Timor-Leste Chess Federation (TLCF)",
  "Togo Chess Federation (FTE)",
  "Trinidad and Tobago Chess Association (TTCA)",
  "Tunisian Chess Federation (FTE)",
  "Turkish Chess Federation (TSF)",
  "Turkmenistan Chess Federation (TCF)",
  "Uganda Chess Federation (UCF)",
  "Ukrainian Chess Federation (UCF)",
  "United Arab Emirates Chess Federation (UAECF)",
  "United States Chess Federation (US Chess)",
  "U.S. Virgin Islands Chess Federation (USVICF)",
  "Uruguayan Chess Federation (FUA)",
  "Uzbekistan Chess Federation (UCF)",
  "Venezuelan Chess Federation (FVA)",
  "Vietnam Chess Federation (VCF)",
  "Chess Wales (CW)",
  "Yemen Chess Federation (YCF)",
  "Chess Association of Zambia (CAZ)",
  "Zimbabwe Chess Federation (ZCF)",
];
